### ISSUE TITLE
[1.4.9b] Osmium not spawning in The End

### ISSUE THREAD

**Issue by Timeslice42** [MechOrigin/NTC2#102]
I have killed the dragon and flown around with the scanner for an hour or two and no osmium has spawned. The JEI tip for Emendates Enigmatica indicates that it should be spawning, but there's nothing.

In an (un?)related issue, I noticed that the laser ore drill entry for osmium, it has every biome in The End blacklisted. Could this be indirectly related?

**Comment by Daykauz** [comment]
Salut , j'ai le même problème , en plus de ça aucun petit portail n'apparait , si quelqu'un a une solution je suis preneur 
merci

**Comment by Dasffion** [comment]
Osmium is extremely rare. Extremely. To make up for this when you do find it you’ll get around 1000 clusters, which are 4 chunks each, which can then be processed further. 

Daykauz, English will be easier to answer as the modpack author speaks English. I ran it through google translate though and if you’re not getting the little portals then you haven’t killed the ender dragon.

**Comment by Daykauz** [comment]
hello, I am sending you this video to prove to you that we have indeed
killed the dragon? but no small portal appears, a bug?


video link :https://www.youtube.com/watch?v=D3UFZyZxhzE

thanks

**Comment by Timeslice42** [comment]
I feel this issue has been sufficiently addressed in 1.5.x, so I'm closing the issue.
