### ISSUE TITLE
Unable to craft Custom Machinery Compact Crafter

### ISSUE THREAD

**Issue by R00KIE42** [MechOrigin/NTC2#104]
Unable to craft the "Compact Crafter" from Custom Machinery.

Front
![image](https://user-images.githubusercontent.com/108621415/177045573-c7579eb1-d64f-41c7-b52f-070e5c60e212.png)

Above
![image](https://user-images.githubusercontent.com/108621415/177045622-7339c23d-d143-4f34-8858-92b112c3a530.png)

There are no other blocks inside the crafting zone. The floor is not in the zone.

I've tried different combinations with the "Field Proxy (Rescan)" (pink) and "Field Proxy (Match)" (green) by switching where the greens and pink are placed.

In the image, the pink block is on the opposite side to the Builder from RFToolsBuilder and 1 block to the right.

The blocks have been rotated to fit the rotation in the preview UI.

The "Space Chamber Controller" is the bottom right corner in the front, to the right of the builder.

![image](https://user-images.githubusercontent.com/108621415/177046020-31949dc1-bf50-4426-ad36-cad35a15b2fc.png)

159 Black Plastic Block - Mekanism: Additions
27 Orange Plastic Block - Mekanism: Additions
7 Space Chamber - RFToolsBuilder
4 Field Projector - Compact Crafting
2 Field Proxy (Match) - Compact Crafting
1 Builder - RFToolsBuilder
1 Field Proxy (Rescan) - Compact Crafting
1 Space Chamber Controller - RFToolsBuilder

Trying to throw an "Ultimate Ingot" in the zone does not start the miniaturization crafting process.

**Comment by MechOrigin** [comment]
siding issue
