### ISSUE TITLE
Free Ultimate Singularity

### ISSUE THREAD

**Issue by R00KIE42** [MechOrigin/NTC2#105]
In the "Package Recipe Encoder" from "Packaged Auto", if you select the "Ultimate Crafting Table", it defaults as a blank crafting recipe, but the result is the "Ultimate Singularity". It allows to add it to the crafting queue and gives free ultimate singularities.

![image](https://user-images.githubusercontent.com/108621415/177082052-6f8dfddb-0e28-46ee-9784-373747d5b950.png)

I found this previously reported bug which seems similar, but used to crash the server - https://github.com/MechOrigin/NTC2/issues/69

Server Type: Forge_1.16.5_36.2.34
Modpack: Not Too Complicated2-1.4.9bRelease

**Comment by MechOrigin** [comment]
fixed 1.5.1
