### ISSUE TITLE
Suggestion Regarding Solar Panel Balance

### ISSUE THREAD

**Issue by i2smrt4u** [MechOrigin/NTC2#107]
The lack of exponentiation in crafting leads to rapid progression through tiers at minimal cost. Maybe each tier should have the products halved. Craft solar panels with four panels of a lower tier, recipe results in two or three solar panels as a result, rather than four solar panels. Currently producing a block of refined obsidian quadruples your power production (some exaggeration for effect).

**Comment by MechOrigin** [comment]
fixed in 1.5.1
