### ISSUE TITLE
"End Resin Processor" need "Endest Pearl" in "Ultimate Crafting Table" what need "Stellar Alloy Ingot" from "End Resin Processor"

### ISSUE THREAD

**Issue by dmitryk1** [MechOrigin/NTC2#110]
May be it's Trouble: to build "End Resin Processor" I need trow "Endest Pearl" to them. "Endest Pearl" maked in "Ultimate Crafting Table" that build from "Ultimate Component" that consist from "Stellar Alloy Ingot" who make in "End Resin Processor". 

What i not see?

**Comment by LotP1** [comment]
use the end resin processor multiblock
there's a quest for it in the custom machinery chapter

**Comment by toruPuchuu** [comment]
I also had this issue. Perhaps making "End Resin Processor" clearly a dependent on "End Resin Processor Controller" would clear this up? They are currently laid out to look like they should be done in reverse...

**Comment by MechOrigin** [comment]
End Resin Processor MK2 not displaying as MK2, the single block machine is obviously only craftable after crafting the multiblock. fixed in 1.5.1
