### ISSUE TITLE
Two recipes for ultimate singularity?

### ISSUE THREAD

**Issue by tornewuff** [MechOrigin/NTC2#114]
In version 1.5.0b there are two different recipes defined for the ultimate singularity:

1) One defined explicitly in ExtendedCrafting.zs, which includes every type of singularity except for Energy Collector MK3 and Slag Block.

2) One defined automatically by the Extended Crafting mod due to the mod's ultimateSingularityRecipe setting being set to true, which includes every type of singularity except for Ultimate Conglomerate and Time in a Bottle.

The mod's automatically defined recipe just takes the first 81 types of singularity that got registered, and there's 83 currently in the pack.

I'm guessing this isn't intentional? Since the automatically defined recipe doesn't include the Ultimate Conglomerate singularity, all the creative items can be crafted without making ultimate conglomerate at all (it's only used to make the infinity armor, and its singularity is only required for the ProjectE amulets).

**Comment by MechOrigin** [comment]
Thanks for the heads up! Yeah I purposely left the default extended crafting generated recipe but not I'm thinking that was a mistake. This will be fixed in 1.5.1
