### ISSUE TITLE
Potential licensing issues related to NTC2 project on github

### ISSUE THREAD

**Issue by Risa-G** [MechOrigin/NTC2#115]
All of the mods in NTC2 are allowed to be in the pack, however, several don't allow or must explicitly allow redistribution outside of the curseforge scope. I've compiled a list of the ones I've found in your modpack, though it may not be the full list, as I may have missed a few.

- Aquaculture 2
- Athenaeum
- Better Compatibility Checker
- Caged Mobs
- Client Tweaks
- Clickable Advancements
- The entire Thermal suite and CoFH Core
- Collective
- Compact Crafting
- Compressium
- Corail Tombstone
- Crafting Tweaks
- Emojiful
- End Portal Recipe
- Entangled
- Entity Culling
- Explosive Arrows
- FancyMenu
- Farming for Blockheads
- Fast Leaf Decay
- Fluid Drawers Legacy
- Flux Networks
- Forgiving Void
- FPS Reducer
- Hammer Lib
- Harvest
- IAP
- IBICF
- Immersive Engineering and Immersive Petroleum
- Industrial Agriculture
- Inventory Statistics
- Item Recycler
- Just Enough Effect Descriptions
- Morpheus
- Nether's Exoticism
- Pam's HarvestCraft 2 Suite
- Pipez
- Productive Beees
- Random Bone Meal Flowers
- Runelic
- Savage Ender Dragon
- Small Ships
- Snowballs Freeze Mobs
- Spice of Life Carrot Edition
- Structure Gel API
- Supermartijn64's libraries
- Tantrum
- Tesseract
- Trash Cans
- Trash Slot
- Upgrade Aquatic

I just want to reiterate that all of these mods are allowed to be in your modpack. The only (potential) issue is your uploading of your modpack to github with all of the binaries included.

**Comment by Dasffion** [comment]
Whytho?

**Comment by Risa-G** [comment]
> Whytho?

Why what?

**Comment by Dasffion** [comment]
Why take the time to do this? Also pretty sure Caged Mobs is wrong, that's the only one I looked at.

**Comment by Risa-G** [comment]
> Why take the time to do this? Also pretty sure Caged Mobs is wrong, that's the only one I looked at.

In double checking caged mobs, yeah I was wrong. As for why I took the time, it's because I'd rather not see licensing issues pop up in projects. 

In checking the project again, optifine is also redistributed, and the dev for optifine takes that pretty seriously.

**Comment by jmarler** [comment]
The license from Microsoft for Minecraft mods doesn't allow distribution to be restricted, so this can safely be ignored.

**Comment by Risa-G** [comment]
> The license from Microsoft for Minecraft mods doesn't allow distribution to be restricted, so this can safely be ignored.

Except it immediately contradicts itself on the next line by saying ownership rights are preserved. The EULA has always been vague, and in situations where the EULA says two opposing things, isn't it better to play it safe regarding licenses?

The fix isn't even complicated. All that needs to be uploaded are the custom scripts, assets, and configs, like how every other modpack uploads changes to GitHub.

**Comment by jmarler** [comment]
Microsoft is the original owner of rights to Minecraft, and also the most likely to bring litigation, so I would agree the best option is to play it safe and not attempt to apply limits to distribution. If any of the mod authors have issues with the distribution of their mods in this modpack, we would better spend our efforts dealing with those issues individually.

**Comment by Buuz135** [comment]
I recommend deleting all the mods in your repo asap or any mod author can take file a DMCA claim agains your repo and take your repo down.

Licenses exist for a reason.

**Comment by MaxNeedsSnacks** [comment]
For the record, there are also just... way less risky (and way less space-intensive) ways to manage mods in your GitHub repo, see InstanceSync, packwiz, pax, AlmostPacked etc.

There has been drama and disputes about this before, and it's generally better to be safe than sorry

**Comment by TelepathicGrunt** [comment]
Also as another modder (even though my mods are in the pack), many modders rely on cursepoints for revenue and have extreme distrust for any other alternative source of their mods. So even the mods with licenses that allow redistribution like this may still rub those modders the wrong way as this redistribution robs them of cursepoints and they cant verify that the user has updated/unaltered version of the mods.

**Comment by MechOrigin** [comment]
I also rely on cursepoints for revenue. But I don't go after alpha builds on GitHub using my code or mods. Eventually this will get posted on curseforge but it makes it 10x more annoying for no reason, other than to not make a few bucks. Regardless.... I don't really care about the risk, or about licensing, Minecraft is a game for fun, you code for fun, Microsoft owns the source now so anybody who develops mods fall under their licensing because it's using their code, which last time I checked is completely open to distribute and whatnot, and you know what, even if im wrong... Take the stick out of your asses and get a life.

On another note, thanks for the heads up. I will choose to respect the wishes of the mod developers to not distribute their mods out of respect. I don't like rubbing anybody the wrong way and I prefer to have good relationships with everyone. So with that being said I will upload a manifest of the modpack pre alpha instead of the actual mods themselves.

I love you all, take care. 

Closed.
