### ISSUE TITLE
Fix Middle Click in AE2 Crafting/Pattern Grid

### ISSUE THREAD

**Issue by zapl** [MechOrigin/NTC2#116]
AE2 Grid conflict with sort middle click from inventory tweaks.

Add to `config\invtweaks-client.toml` or replace to fix this.

AE2 moved code around and it's no longer `appeng.container.implementations.*`, see https://github.com/AppliedEnergistics/Applied-Energistics-2/tree/8.4.x-1.16.x/src/main/java/appeng/container/me/items

```
	[[sorting.containerOverrides]]
		containerClass = "appeng.container.me.items.CraftingTermContainer"
		sortRange = ""

	[[sorting.containerOverrides]]
		containerClass = "appeng.container.me.items.PatternTermContainer"
		sortRange = ""

	[[sorting.containerOverrides]]
		containerClass = "appeng.container.me.items.WirelessTermContainer"
		sortRange = ""
```

**Comment by LindaJuffermans** [comment]
Or change the keybinds in your options so there aren't any conflicts.

**Comment by zapl** [comment]
It's more than a keybind conflict, AE2s interfaces handle middleclicks in a fixed manner and apparently with lower precedence than inventory tweaks and that part isn't configurable.
Sure you could change inventory tweaks to use a different sort key but this change here actually fixes the interaction between those mods the way inventory tweaks intends it - by telling inventory tweaks to ignore those AE2 interfaces.
The config that comes in the modpack already does that for AE2 but AE2 changed recently and they renamed their interfaces so the config in inventory tweaks is outdated and only knows about their old names.

**Comment by MechOrigin** [comment]
This is excellent, thank you @zapl <3 I will add this change to 1.5.1
