### ISSUE TITLE
[Productive bees] - Pink slime comb 

### ISSUE THREAD

**Issue by Luthys** [MechOrigin/NTC2#119]
Hi, 

v: 1.5.0b-r

The Pink slime comb does not give anything when you put it in the centrifuge.

![image](https://user-images.githubusercontent.com/20166934/182267589-a9fc4b78-1ce8-49be-9f1b-64ba0b6c7844.png)

Edit: 
On local i see the recipe that gives me pink slime (liquid) but on my server the recipe gives nothing. But it's the same version...

Thx !

**Comment by MechOrigin** [comment]
Strange, the mod itself should add this recipe not the modpack as it's in the data in the productive bees jar itself. I will add it to the modpacks datapack structure and that should fix the issue.
