### ISSUE TITLE
Mekanism - Nuclear Waste quest checks for wrong Plutonium Pellet

### ISSUE THREAD

**Issue by quietust** [MechOrigin/NTC2#13]
Modpack version: 1.3.9

The Mekanism quest titled "Nuculer dummy, the S is silent" requires you to collect either a Polonium Pellet or a Plutonium Pellet, but the Plutonium Pellet has been replaced by the (Nuclearcraft-style) "Plutonium-242" item.

Fortunately, the quest only requires you to collect one of the two, and subsequent quests require you to make both anyways.

**Comment by MechOrigin** [comment]
Removed the requirement of NC plutonium-242 and added item tag to both plutoniums
