### ISSUE TITLE
Cannot use RFTools Machine Infuser, does not accept Dimensional Shards

### ISSUE THREAD

**Issue by quietust** [MechOrigin/NTC2#18]
Modpack version: 1.3.9

The RFTools Machine Infuser only accepts its own Dimensional Shards (McJtyMods/RFToolsBase#34), and because this pack replaces them with the ones from Emendatus Enigmatica, it is not possible to infuse any machines.

This same issue also affected the Enigmatica 6 modpack, where it was solved by adding a custom crafting recipe to convert them back (EnigmaticaModpacks/Enigmatica6#776). Strangely, if I try to `/give` myself the shards from RFToolsBase, they get automatically converted to the ones from EmendatusEnigmatica.

**Comment by MechOrigin** [comment]
I've fixed this now by basically doing the same thing as EE6 and adding a crafting recipe, and blacklisting the automatic oredict conversion
