### ISSUE TITLE
Flux dust EMC is not balanced

### ISSUE THREAD

**Issue by ali-abz** [MechOrigin/NTC2#21]
Hey there,
So I just noticed that flux dust emc is 512 and since the main ingredient is redstone dust (64 emc), that means with each redstone converted to flux dust, there would be a 448 emc difference (8x). With a full inventory of redstone dust and 4 obsidian, you can profit about 250k emc with ease. I think this is not intended and does not go with the balanced theme of the pack.

**Comment by MechOrigin** [comment]
changed to 64emc to be the same as redstone
