### ISSUE TITLE
induction cells from Mek are extremely expensive (like 170 steel casings at the minimum)

### ISSUE THREAD

**Issue by MechOrigin** [MechOrigin/NTC2#28]
fix induction cells requiring steel casings

**Comment by AndreiPurcaru** [comment]
For the basic induction cell you only need a single casing. I feel that the cost currently enables you to get into it decently easy (I mean you still need to process lithium and that's a pain) but it demands automation if you want the highest tier. I would say its fair but it's your call in the end.
