### ISSUE TITLE
Colossal Stars Omega infeasible to craft without intermediate EMC

### ISSUE THREAD

**Issue by quietust** [MechOrigin/NTC2#36]
Pack version: 1.3.9

This pack removed the EMC values from nearly all "compound" items (except for the various tiers of colored Matter from ProjectE+ProjectEX), and this included all of the Klein Star tiers, requiring the player to craft all of the bottom-tier ones and upgrade them.

For the Klein Star Omega this only takes a few minutes, and with the Magnum Star Omega (needed for the Infused Armor) this can be done easily in a few hours using automation, but the Colossal Star Omega requires crafting over 17 _billion_ Klein Stars Ein which takes an infeasibly long time to finish.

On my server (running on a Core i7-4790), the fastest I was able to manage was 32 RFTools Crafters (tier 3), each crafting 25 Klein Stars Ein per tick (and upgrading them to Drei because they only have 4 output slots), all fed by 18 Energy Condensers Mk2 with Pipez extracting from every side, and that would've taken just under 2 weeks of nonstop running per Colossal Star Omega (but you need 4, so make that 52 days). Unfortunately, running that many Energy Condensers and Ultimate-upgraded Extracting Item Pipez causes enough lag to slow my server down to about 16 TPS, so it would actually take closer to 65 days in total.

All other methods of autocrafting and item transport I tried (Thermal, Mekanism, and Integrated Dynamics) were significantly slower, so I don't see how it's feasible to actually craft the Infinity Armor as the pack currently stands.

**Comment by quietust** [comment]
One possible suggestion: giving the Colossal Star Ein its original EMC value of 412,316,860,416 would still require the use of autocrafting to craft the 4 Magnum Stars Omega for crafting the Infused Armor plus 4 more to combine into Colossal Star Ein, and from there it would just be a matter of gathering about 1.7 quadrillion EMC to craft all of the Colossal Stars Omega (which is easily achievable in this pack).

**Comment by quietust** [comment]
This appears to have been addressed by changes in pack version 1.4.0.

**Comment by Dasffion** [comment]
All Omega's have EMC values in 1.4.1 (Updated after your last post). This issue can be closed as you can easily create the intermediate tiers after having made one of each Omega.
