### ISSUE TITLE
[1.4] AEInfinityBooster expects AE2 8.4.4 (on 1.16)

### ISSUE THREAD

**Issue by Kausta** [MechOrigin/NTC2#46]
New Applied Energistics version is 8.4.7 but AEInfinityBooster only works with AE2 8.4.4.
This results in a crash with any previously placed wireless access points.
(Reference issues: [https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6077](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6077), [https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6028](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6028)).
Removing the mod works, and it isn't required with the Wireless Crafting Terminals anyways.

**Comment by MechOrigin** [comment]
removed aeinfinitybooster for 1.4.1
