### ISSUE TITLE
Various recipes require Sulfur Dust instead of Yellow Dye

### ISSUE THREAD

**Issue by quietust** [MechOrigin/NTC2#6]
Modpack version: 1.3.9

While looking through some Pam's Harvestcraft 2 food recipes, I noticed a few (notably "Marshmellow Chicks" and "Epic Bacon") were requiring Sulfur Dust. Upon searching further, I noticed that nearly *all* of the crafting recipes which currently demand Sulfur Dust are ones that would normally expect to use some sort of Yellow Dye.

I can only assume that the KubeJS scripts being used to unify the various Sulfur Dust items from Thermal/Immersive/Mekanism into Emendatus Enigmatica are incorrectly targetting recipes tagged to use `forge:dyes/yellow` (or even just `forge:dyes`) and changing them to demand the `emendatusenigmatica:sulfur_dust` item.

**Comment by quietust** [comment]
This is probably the same reason why every single AE2 recipe which originally requested Certus Quartz now requires Charged Certus Quartz - the old recipes used tags to accept Normal/Pure/Charged Certus Quartz, but `kubejs/server_Scripts/NTC/base/modrecipes/general/replace_input.js` is changing them to all explicitly requre the Charged version from Emendatus Enigmatica.

This also explains why Pure Certus Quartz and Pure Fluix crystals have almost no crafting uses - the only recipes which accept them are the ones that originally *required* them (and wouldn't accept the normal ones).

**Comment by AndreiPurcaru** [comment]
I also encountered a similar problem today. I think there are some problems with a few tags in the kubejs configuration. This is probably what also caused #15.
