### ISSUE TITLE
Suggestion: Possibility to craft dragon's breath with different dragon scales

### ISSUE THREAD

**Issue by acelel** [MechOrigin/NTC2#64]
As the title suggests, there are 4 different dragon scale drops from the caged mobs but only one of them works to make dragon's breath.

A lot of end game chemistry requires dragon's breath and it is currently very tedious to farm (relevant drop from caged mob's is very low and the other scales are useless).

Maybe the drops could be unified into one or a different recipe for dragon's breath could be added.

**Comment by acelel** [comment]
I suppose you can just craft the oganesson through fusion but that doesn't seem that fun considering you already need to craft half of the elements that way

**Comment by MechOrigin** [comment]
Good idea, I will add the other scales to craft dragons breath

**Comment by MechOrigin** [comment]
Updated in 1.4.3
