### ISSUE TITLE
Watch of Flowing Time has no recipe?

### ISSUE THREAD

**Issue by iambenmitchell** [MechOrigin/NTC2#65]
I am trying to craft the `Watch of Flowing Time` from `ProjectE` but it has no recipe? Has it been disabled? I noticed that Direwolf20 can craft it in his videos.

**Comment by TrevorCow** [comment]
Direwolf20 enabled the recipe himself as it was disabled on and below 1.3.9. However, in version 1.4 and up there is a custom recipe for it.

**Comment by iambenmitchell** [comment]
Our server is on 1.4.1 and it is still disabled. Perhaps we need to manually enable it?

**Comment by Kithio** [comment]
The recipe is enabled by default on a fresh install of 1.4.1, only reason it'd be "disabled" is if you manually updated the pack and forgetting to overwrite or add in some files

**Comment by MechOrigin** [comment]
Indeed you folks are correct. Closing this
