### ISSUE TITLE
Magma Crucible Unable to Melt Certus Quartz

### ISSUE THREAD

**Issue by aiantas91** [MechOrigin/NTC2#66]
Hey there, perhaps the recipe changed and i didnt noticed apologies if thats the case. In the past im pretty sure i've melted certus quartz in the magma crucible then outputed in the liquid encapsulator with Lightning charges to make Charged Certus Quartz but after the latest update it doesnt work.

Thanks for the pack and your work as i've enjoyed playing.

**Comment by Th3G0old3enKill3r** [comment]
I can confirm this not only that but fluix has changed to fluix crystal and charged certus quartz has changed to charged certus quartz crystal
you can renable the recipe if you know your way around crafttweaks it's still there just remove the // in script/thermal.cz line 73 and type in chat with cheat mode /reload and wait until it tell you that its completed

**Comment by MechOrigin** [comment]
Fixed for alpha 1.4.4
