### ISSUE TITLE
Suggestion: Industrial Foregoing Essence to Mini Utilities Experience Pearl

### ISSUE THREAD

**Issue by Overseer9** [MechOrigin/NTC2#67]
Since experience pearl had singularity in version 1.4.2, it will be great if there is more way to obtain experience pearl.

Industrial Foregoing essence can be used on mob duplicator to spawn mobs that can drop experience pearls. But mobs are entities that can cause lags in large number.

I suggest to make custom crafting recipe, that turns 1 bucket of industrial foregoing essence into 4 experience pearls dirrectly

**Comment by MechOrigin** [comment]
Added thermal chiller recipe. There are experience essence farms such as mystal agri and bees
