### ISSUE TITLE
Server hangs on Preparing level "world" 1.4.2/1.4.3

### ISSUE THREAD

**Issue by toastonrye** [MechOrigin/NTC2#68]
Ironically I am finding creating a server to be "too complicated". I'm used to packs like E2E where the server is pre-packaged.

So, my steps as I've missed something:

Downloaded and merged 2 versions, 1.4.2 and 1.4.3 because 1.4.3 looks to be missing files.
Windows 10, another PC in my home I run my modpacks on.
CPU and memory usage is less than 50% entire time.
The last console message is [18:09:10] [Server thread/INFO] [minecraft/DedicatedServer]: Preparing level "world"

Edit:
So I haven't been able to isolate and figure out what's going on. I downloaded a previous version 1.4.1 and it still hangs at preparing level world.

I downloaded another 1.16.5 pack, create above and beyond, used the same server bat file and modified the forge version and it launched with no issues quickly...

I was going to do a binary search, removing half the mods at a time to try and see, but with all the libraries and dependencies that is a task!

**Comment by sethioy** [comment]
I have a similar issue. Extracted and ran .bat file for server 1.4.4. The launcher hangs on Preparing level "world".

**Comment by Elyspio** [comment]
You can create a world in solo and use it on server

**Comment by MechOrigin** [comment]
It takes about 10-20 minutes on some machines. You just have to wait. No need to remove anything, it's a forge caching thing.
