### ISSUE TITLE
PackagedAuto/PackagedExAuto ultimate singularity bug

### ISSUE THREAD

**Issue by Will11690** [MechOrigin/NTC2#69]
Upon selecting the Ultimate Crafting recipe in the Package Recipe Manager it defaults to an ultimate singularity recipe with no inputs but the singularity loaded into the output and recipe icon, but upon adding the singularities to the manager via JEI or manually the icon and output is blank and saving either one(the recipe with no icon or output / or the one with the output and no recipe) causes the AE system to glitch out and not show any autocrafting recipes and eventually leads to a game crash upon trying to break the controller, packager/unpackager or remove the package recipes from the packager/unpackager.

NOTE: This is running on a private server I am hosting for me and my friend and this may have been caused by an improper update from 1.3.9 but I am unsure of that as of this moment but I wanted to post this anyways as others may be experiencing the same issue. I will look into this more tomorrow after I get up to see if it was an updating issue.

**Comment by Will11690** [comment]
It seems to be an issue with the recipe on server side. If I add the recipe in single player then move the world back to my server it allows the recipe and allows everything to work normal EXCEPT it causes all clients trying to connect to the server to get stuck on Encrypting. I'm unsure if there is a way to fix this on the pack though.

**Comment by Xerosaber** [comment]
Apologies for the necro. I am also experiencing this issue, and it is preventing my server from starting at this point. I did the exact same thing as OP. I broke the ME Controller (at least a couple of blocks of it) to try and fix the crafting glitch, and have not been able to stabilize the server since.
