### ISSUE TITLE
Server exception IndexOutOfBoundException on loading world

### ISSUE THREAD

**Issue by Arthuret** [MechOrigin/NTC2#72]
Hello,
I am trying to run the 1.4.2 server. It launches and load normally, but when I try to connect to it, an exception "Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ArrayIndexOutOfBoundsException: 5" is thrown, and the connection fail.

Setup : fresh server, java 11 and 8 gives the same result. (aarch64, 6Gb allocated to java); Both server and client uses v 1.4.2 of the pack.
Client downloaded using curseForge launcher. (No 1.4.3 server version ?)

Thanks

**Comment by LotP1** [comment]
this has just been fixed in version 1.4.4 :)

**Comment by MechOrigin** [comment]
This was an issue with a compact machines recipe, we've opened a ticket on CM github. Fixed on our end for the time being. Closing
