### ISSUE TITLE
Blast Chiller recipes

### ISSUE THREAD

**Issue by klobass** [MechOrigin/NTC2#8]
NTC 1.3.9

Thermals Blast chiller recipes are really weird -  it creates everything (gears, ingots, rods, plates - heck it even creates nugets) from one bucket (1000mb) but when one ingot is melted it produces only 144mb so math really does not add up here..
![unknown](https://user-images.githubusercontent.com/31200493/159909333-6ffbce62-9b95-4e23-97ed-239bdc5cc021.png)
.

**Comment by quietust** [comment]
This is most likely a bug in the CoFH Core mod, since another modpack I played recently suffered from the exact problem, and upgrading said mod to version 1.16.5-1.4.1.8 fixed the problem.

**Comment by klobass** [comment]
> This is most likely a bug in the CoFH Core mod, since another modpack I played recently suffered from the exact problem (see [simibubi/Above-and-Beyond#264](https://github.com/simibubi/Above-and-Beyond/issues/264)), and upgrading said mod to version 1.16.5-1.4.1.8 fixed the problem.

yes solved

**Comment by quietust** [comment]
You should probably leave this issue open until the modpack itself is officially updated.
