### ISSUE TITLE
Consistent Crash

### ISSUE THREAD

**Issue by chemban** [MechOrigin/NTC2#80]
https://pastebin.com/m4UpVxPK

I have updated everything that could be all the way down to bios.  This happens randomly between 5 min and 30.  I have tried full screen and windowed, reinstalling java and minecraft, Curseforge and MultiMC.  I can sit Idle for hours nothing happens.  If I start moving around it will fault within 5 min.  This in itself is just annoying but it also resets about 5 minutes.

**Comment by Dasffion** [comment]
The pastebin doesn’t work.

**Comment by chemban** [comment]
Ya Im not sure whats going on there.
I can paste it here if that's ok.

**Comment by chemban** [comment]
[hs_err_pid2568.log](https://github.com/MechOrigin/NTC2/files/8696541/hs_err_pid2568.log)

**Comment by LindaJuffermans** [comment]
What would be more useful are the newest file in `minecraft/crash-reports/` as well as the `minecraft/logs/latest.log`

**Comment by chemban** [comment]
It doesn't generate a crash report.  I tried giving it less memory last night and that seems to have fixed the problem.  I am not sure so I would like to do another test run this afternoon to see if the conflict has been rectified.

[latest.log](https://github.com/MechOrigin/NTC2/files/8699129/latest.log)

**Comment by chemban** [comment]
Well by all appearances it seems like either this pack or my system doesn't like giving 8gb to Java.  From what I was able to google java was attempting to access memory that it didn't have permission for.  I have 32 started at 8 went to 16 and this issue was non stop.  gave it 6 and its stable.
