### ISSUE TITLE
Mechanical Placer can dupe every item

### ISSUE THREAD

**Issue by Flumel** [MechOrigin/NTC2#81]
By right clicking a Mechanical placer with a crescent hammer you get a carbon copy of that Mechanical placer + its inventory dropped and the one you already had still exists in the world, therefore you duped an entire 9 slot inventory at once.

Here's a video to show the glitch
https://www.youtube.com/watch?v=7Vwq8oN4f2s

**Comment by MechOrigin** [comment]
fixed, closing
