### ISSUE TITLE
Can't craft ME controller from Applied Energistics with compact crafting

### ISSUE THREAD

**Issue by proyb213** [MechOrigin/NTC2#83]
Whenever i try building the ME controller and i trow the vibrant glass nothing happens.

**Comment by LindaJuffermans** [comment]
Can you share a screenshot of the tooltips for each block you used as well as some screenshots of the build layout?

**Comment by proyb213** [comment]
I tried deleting the pack and installing it again and now it works lol

**Comment by MechOrigin** [comment]
closing because it's probably a CF issue
