### ISSUE TITLE
Speculative Circuit eats Universal Press when using a Circuit Etcher

### ISSUE THREAD

**Issue by ChromaLux** [MechOrigin/NTC2#87]
When crafting a Speculation Core x64 and Universal Press together in the Circuit Etcher, it produces the Printed Speculative Circuit but at the cost of the entire Universal Press. This functionality is different in the generic inscriber, as the press is not consumed.

**Comment by MechOrigin** [comment]
This is an unintended side affect of the kubejs recipe and there is no effective way to fix this. Just going to remove the etcher recipe. closing
