### ISSUE TITLE
Basic Power Flower [MK1] + Tome of Knowledge + Matter Upgrader = Very, Very OP

### ISSUE THREAD

**Issue by ChromaLux** [MechOrigin/NTC2#94]
Crafting and learning a Tome of Knowledge, and then crafting and placing a Basic Power Flower [MK1], and then crafting and using a Matter Upgrader on the Basic Power Flower allows you to upgrade it to any tier power flower at 0 cost, including final. I feel like this might be unintended.

**Comment by MechOrigin** [comment]
Definately unintended. Fixed in 1.4.9. closing
