### ISSUE TITLE
Can dupe any 3x3 craftable item.

### ISSUE THREAD

**Issue by Truetech000** [MechOrigin/NTC2#97]
first time submitting bug but this one is pretty simple. anything i craft in my backpack with a crafting upgrade can be duped if you pick up the item from the output. shift clicking the item reacts like normal. if you click the output it puts the item in your cursor, and also throws the same thing on the ground. this one is pretty bad as you can effectively get infinite of some items. example: craft a block of iron and get 2, then turn them back into ingots and get 27, rinse and repeat.

**Comment by jinkhya** [comment]
Hello, indeed this seems to be a known issue ; Sophisticated Backpack author suggests using the other FastWorkBench mod instead : https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/445#issuecomment-1076022350

**Comment by MechOrigin** [comment]
fixed in 1.5.1
