### ISSUE TITLE
Cant craft single block compact crafter

### ISSUE THREAD

**Issue by LordofBadger** [MechOrigin/NTC2#98]
Hello I am not sure if I am missing something but I have been over the layout to make the single block compact crafter and I cannot form it. The compaction just wont happen. I have every single block EXACTLY the same as in the diagram including the specific rotations to the projectors and builder etc - I was using the ultimate ingot block but since this issue updated the world and have tried with the single ingot I cannot work out what is causing the issue

**Comment by zapl** [comment]
Worked for me in the end but the issue I had was after enlarging the area, that my Field Projectors where too low so they had the ground within their highlighted area. My floor blocks obviously aren't part of the recipe so it didn't detect the correct recipe. I.e. make sure you actually have only the structure in the area. Maybe that's it. Or maybe a torch or something
